name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Docker Compose Plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin
        docker compose version

    - name: Run Tests
      run: |
        cd backend
        go test ./...

    - name: Build with Docker Compose
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        docker compose config
        docker compose build --no-cache

    - name: Test Docker Compose
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        docker compose up -d
        sleep 20
        curl -f http://localhost:8080/health || exit 1
        curl -f http://localhost:8080/weather?lat=51.5074&lon=-0.1278 || exit 1
        docker compose down 