name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Run Tests
      run: |
        cd backend
        go test ./...

    - name: Build Backend
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        cd backend
        docker build -t weather-app-backend .

    - name: Build Frontend
      run: |
        cd frontend
        docker build -t weather-app-frontend .

    - name: Test Application
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        docker network create weather-app-network
        docker run -d --name redis --network weather-app-network redis:alpine
        sleep 5
        docker run -d --name backend --network weather-app-network -p 8080:8080 -e REDIS_HOST=redis -e REDIS_PORT=6379 -e OPENWEATHER_API_KEY=$OPENWEATHER_API_KEY weather-app-backend
        docker run -d --name frontend --network weather-app-network -p 80:80 weather-app-frontend
        
        # Wait for health endpoint to be ready
        for i in {1..30}; do
          if curl -s -f http://localhost:8080/health > /dev/null; then
            echo "Health endpoint is ready"
            break
          fi
          if [ $i -eq 30 ]; then
            echo "Health endpoint failed to become ready"
            exit 1
          fi
          echo "Waiting for health endpoint... ($i/30)"
          sleep 2
        done
        
        # Test weather endpoint
        curl -f http://localhost:8080/weather?lat=51.5074&lon=-0.1278 || exit 1
        
        # Cleanup
        docker stop frontend backend redis
        docker rm frontend backend redis
        docker network rm weather-app-network 